[workspace]
channels = ["pytorch", "nvidia", "conda-forge"]
channel-priority = "disabled"
name = "advanced_robotic_systems"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.8"

[tasks]
gen-test-data  = "python _0_gen_data.py"
extract-frames = "python _1_extract_frames.py"
convert-masks  = "python _2_convert_masks.py"
train          = "python _3_train.py"
infer          = "python _4_infer.py"
check          = "python _5_check.py"
pipeline-test  = { depends-on = ["gen-test-data", "convert-masks", "train"] }
app            = "python app_v4.py"

[dependencies]
python          = "3.12.*"
pip             = ">=26.0.1,<27"
pytorch-gpu     = ">=2.7,<3"
torchvision     = ">=0.22,<1"
cuda-version    = "12.8.*"
pillow          = ">=11.3.0,<13"
setuptools      = "<80"
huggingface_hub = ">=1.5.0,<2"
iopath          = ">=0.1.10,<0.2"
einops          = ">=0.8.2,<0.9"
pycocotools     = ">=2.0.11,<3"
psutil          = ">=7.2.2,<8"
ftfy            = ">=6.3.1,<7"
sam3            = ">=0.1.0.20251211,<0.2"
ffmpeg          = ">=7.0,<8"

[pypi-dependencies]
decord          = ">=0.6.0,<0.7"
opencv-python   = ">=4.13.0.92,<5"
sentencepiece   = ">=0.2.1,<0.3"
imageio         = { version = ">=2.37.2,<3", extras = ["pyav"] }
matplotlib      = "*"
accelerate      = ">=1.13.0,<2"
kernels         = ">=0.12.2,<0.13"
gradio          = { version = ">=6.8.0,<7", extras = ["mcp"] }
spaces          = ">=0.26.0,<0.27"
numpy           = "*"
peft            = ">=0.18.1,<0.19"
torch           = "*"
scikit-image    = ">=0.26.0,<0.27"
scikit-learn    = ">=1.8.0,<2"
ultralytics     = ">=8.3.0,<9"
#transformers   = ">=4.57.0,<5"
